/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_gustavopineda;

import java.awt.Color;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Usuario
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_persona = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        tf_nombreP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_nacionalidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        s_edad = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        rb_m = new javax.swing.JRadioButton();
        rb_f = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        tf_vocacion = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rb_simon = new javax.swing.JRadioButton();
        rb_noviembre = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        rb_pos = new javax.swing.JRadioButton();
        rb_nega = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jd_pais = new javax.swing.JDialog();
        jb_pais = new javax.swing.JButton();
        tf_nombrePa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_himno = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jdc_fundacion = new com.toedter.calendar.JDateChooser();
        jb_colorb = new javax.swing.JButton();
        bg_genero = new javax.swing.ButtonGroup();
        bg_titulo = new javax.swing.ButtonGroup();
        bg_covid = new javax.swing.ButtonGroup();
        popup1 = new javax.swing.JPopupMenu();
        popup1_agregar = new javax.swing.JMenuItem();
        popup1_modificar = new javax.swing.JMenuItem();
        popup1_eliminar = new javax.swing.JMenuItem();
        popup2 = new javax.swing.JPopupMenu();
        popup2_agregar = new javax.swing.JMenuItem();
        popup2_modificar = new javax.swing.JMenuItem();
        popup2_eliminar = new javax.swing.JMenuItem();
        popup3 = new javax.swing.JPopupMenu();
        popup3_agregar = new javax.swing.JMenuItem();
        popup3_modificar = new javax.swing.JMenuItem();
        popup3_eliminar = new javax.swing.JMenuItem();
        popup4 = new javax.swing.JPopupMenu();
        popup4_agregar = new javax.swing.JMenuItem();
        popup4_modificar = new javax.swing.JMenuItem();
        popup4_eliminar = new javax.swing.JMenuItem();
        jd_arbol = new javax.swing.JDialog();
        cb_pais = new javax.swing.JComboBox<>();
        cb_personas = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jb_agregarP = new javax.swing.JButton();
        jb_agregarPa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_paises = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_covid = new javax.swing.JTree();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jl_hombres1 = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_mujeres1 = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jl_pais = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel4.setText("Nombre:");

        jLabel5.setText("Apellido:");

        jLabel6.setText("Nacionalidad:");

        jLabel7.setText("Edad:");

        s_edad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 150, 1));

        jLabel8.setText("Genero:");

        bg_genero.add(rb_m);
        rb_m.setText("M");

        bg_genero.add(rb_f);
        rb_f.setText("F");

        jLabel9.setText("Vocacion:");

        jLabel10.setText("Titulo:");

        bg_titulo.add(rb_simon);
        rb_simon.setText("Si");

        bg_titulo.add(rb_noviembre);
        rb_noviembre.setText("No");

        jLabel11.setText("Covid:");

        bg_covid.add(rb_pos);
        rb_pos.setText("Positivo");

        bg_covid.add(rb_nega);
        rb_nega.setText("Negativo");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Agregar Persona");

        javax.swing.GroupLayout jd_personaLayout = new javax.swing.GroupLayout(jd_persona.getContentPane());
        jd_persona.getContentPane().setLayout(jd_personaLayout);
        jd_personaLayout.setHorizontalGroup(
            jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_personaLayout.createSequentialGroup()
                .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_personaLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_personaLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(s_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_personaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_apellido))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_personaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_personaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(87, 87, 87)
                        .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_personaLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_m)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_f))
                            .addGroup(jd_personaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_simon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_noviembre)
                                .addGap(60, 60, 60))
                            .addGroup(jd_personaLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_pos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_nega))
                            .addGroup(jd_personaLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_vocacion))))
                    .addGroup(jd_personaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(137, 137, 137)))
                .addGap(106, 106, 106))
            .addGroup(jd_personaLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jd_personaLayout.setVerticalGroup(
            jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_personaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_personaLayout.createSequentialGroup()
                        .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_nombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(s_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_personaLayout.createSequentialGroup()
                        .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(rb_f)
                            .addComponent(rb_m))
                        .addGap(18, 18, 18)
                        .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tf_vocacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(rb_simon)
                            .addComponent(rb_noviembre))
                        .addGap(18, 18, 18)
                        .addGroup(jd_personaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(rb_pos)
                            .addComponent(rb_nega))))
                .addGap(76, 76, 76)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        jb_pais.setText("Agregar");
        jb_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_paisActionPerformed(evt);
            }
        });

        jLabel16.setText("Nombre:");

        jLabel17.setText("Fecha de Fundacion:");

        jLabel18.setText("Color de Bandera:");

        jLabel21.setText("Nombre del Himno:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel24.setText("Agregar Pais");

        jb_colorb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_colorbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_paisLayout = new javax.swing.GroupLayout(jd_pais.getContentPane());
        jd_pais.getContentPane().setLayout(jd_paisLayout);
        jd_paisLayout.setHorizontalGroup(
            jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_paisLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_paisLayout.createSequentialGroup()
                        .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_paisLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_nombrePa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_paisLayout.createSequentialGroup()
                                .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_himno, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jd_paisLayout.createSequentialGroup()
                                        .addComponent(jb_colorb, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                        .addComponent(jb_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(122, 122, 122))
                    .addGroup(jd_paisLayout.createSequentialGroup()
                        .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_paisLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdc_fundacion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_paisLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel24)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jd_paisLayout.setVerticalGroup(
            jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_paisLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 24, Short.MAX_VALUE)
                .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_nombrePa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdc_fundacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_paisLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jb_colorb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_paisLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jd_paisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tf_himno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153))
        );

        popup1_agregar.setText("Agregar");
        popup1.add(popup1_agregar);

        popup1_modificar.setText("Modificar");
        popup1_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup1_modificarActionPerformed(evt);
            }
        });
        popup1.add(popup1_modificar);

        popup1_eliminar.setText("Eliminar");
        popup1_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup1_eliminarActionPerformed(evt);
            }
        });
        popup1.add(popup1_eliminar);

        popup2_agregar.setText("Agregar");
        popup2.add(popup2_agregar);

        popup2_modificar.setText("modificar");
        popup2_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup2_modificarActionPerformed(evt);
            }
        });
        popup2.add(popup2_modificar);

        popup2_eliminar.setText("eliminar");
        popup2_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup2_eliminarActionPerformed(evt);
            }
        });
        popup2.add(popup2_eliminar);

        popup3_agregar.setText("Agregar");
        popup3.add(popup3_agregar);

        popup3_modificar.setText("Modificar");
        popup3_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup3_modificarActionPerformed(evt);
            }
        });
        popup3.add(popup3_modificar);

        popup3_eliminar.setText("Eliminar");
        popup3_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup3_eliminarActionPerformed(evt);
            }
        });
        popup3.add(popup3_eliminar);

        popup4_agregar.setText("Agregar");
        popup4.add(popup4_agregar);

        popup4_modificar.setText("Modificar");
        popup4_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup4_modificarActionPerformed(evt);
            }
        });
        popup4.add(popup4_modificar);

        popup4_eliminar.setText("Eliminar");
        popup4_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popup4_eliminarActionPerformed(evt);
            }
        });
        popup4.add(popup4_eliminar);

        jButton4.setText("Agregar al Arbol");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_arbolLayout = new javax.swing.GroupLayout(jd_arbol.getContentPane());
        jd_arbol.getContentPane().setLayout(jd_arbolLayout);
        jd_arbolLayout.setHorizontalGroup(
            jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_arbolLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(cb_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(jd_arbolLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButton4)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jd_arbolLayout.setVerticalGroup(
            jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_arbolLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jd_arbolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jButton4)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_agregarP.setText("Agregar");
        jb_agregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarPActionPerformed(evt);
            }
        });

        jb_agregarPa.setText("Agregar");
        jb_agregarPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_agregarPaActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Paises");
        jt_paises.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_paises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_paisesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_paises);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Paises");
        jt_covid.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_covid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_covidMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_covid);

        jButton3.setText("---->");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Administracion");

        jLabel2.setText("Persona:");

        jLabel3.setText("Pais:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Lista de Mujeres");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Lista de Hombres");

        jl_hombres1.setModel(new DefaultListModel());
        jScrollPane6.setViewportView(jl_hombres1);

        jl_mujeres1.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(jl_mujeres1);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Lista de Paises");

        jl_pais.setModel(new DefaultListModel());
        jScrollPane8.setViewportView(jl_pais);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Arbol de Paises");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Arbol Coronavirus");

        jButton2.setText("Agregar al Arbol");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_agregarP)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_agregarPa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel25)
                        .addGap(142, 142, 142)
                        .addComponent(jLabel26)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jb_agregarPa)
                    .addComponent(jLabel2)
                    .addComponent(jb_agregarP))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane8)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(90, 90, 90)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultComboBoxModel mc = (DefaultComboBoxModel) cb_pais.getModel();
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_personas.getModel();
        DefaultTreeModel modeloC = (DefaultTreeModel) jt_covid.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloC.getRoot();
        cb_pais.getSelectedIndex();
        String nombre = cb_pais.getSelectedItem().toString();
        String genero = ((Persona) m.getSelectedItem()).getGenero();

        int centinela = -1;
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().equals(nombre)) {
                if (((Persona) m.getSelectedItem()).getCovid().equals("Positivo")) {
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(cb_personas.getSelectedItem());
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                    centinela = 1;
                }
            }
        }

        if (centinela == -1) {
            DefaultMutableTreeNode n = new DefaultMutableTreeNode(nombre);
            if (((Persona) m.getSelectedItem()).getCovid().equals("Positivo")) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(cb_personas.getSelectedItem());
                n.add(p);
            }
            raiz.add(n);
        }

        jd_arbol.setVisible(false);
        modeloC.reload();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jb_colorbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_colorbActionPerformed
        jb_colorb.setBackground(JColorChooser.showDialog(this, "Seleccione color: ", Color.yellow));
        color = jb_colorb.getBackground();
    }//GEN-LAST:event_jb_colorbActionPerformed

    private void jb_agregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarPActionPerformed
        jd_persona.setModal(true);
        jd_persona.pack();
        jd_persona.setLocationRelativeTo(this);
        jd_persona.setVisible(true);
    }//GEN-LAST:event_jb_agregarPActionPerformed

    private void jb_agregarPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_agregarPaActionPerformed
        jd_pais.setModal(true);
        jd_pais.pack();
        jd_pais.setLocationRelativeTo(this);
        jd_pais.setVisible(true);
    }//GEN-LAST:event_jb_agregarPaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultListModel modelo = (DefaultListModel) jl_hombres1.getModel();
        DefaultListModel modelo2 = (DefaultListModel) jl_mujeres1.getModel();
        String titulo;
        String covid;
        if (rb_simon.isSelected()) {
            titulo = "Verdadero";
        } else {
            titulo = "Falso";
        }
        if (rb_pos.isSelected()) {
            covid = "Positivo";
        } else {
            covid = "Negativo";
        }
        if (rb_m.isSelected()) {
            String genero = "Hombre";
            Persona x = new Persona(tf_nacionalidad.getText(), tf_nombreP.getText(), tf_apellido.getText(), (Integer) s_edad.getValue(), genero, tf_vocacion.getText(), titulo, covid);
            modelo.addElement(x);
            DefaultComboBoxModel m = (DefaultComboBoxModel) cb_personas.getModel();
            m.addElement(x);
        } else {
            String genero = "Mujer";
            Persona x = new Persona(tf_nacionalidad.getText(), tf_nombreP.getText(), tf_apellido.getText(), (Integer) s_edad.getValue(), genero, tf_vocacion.getText(), titulo, covid);
            modelo2.addElement(x);
            DefaultComboBoxModel m = (DefaultComboBoxModel) cb_personas.getModel();
            m.addElement(x);
        }
        jl_hombres1.setModel(modelo);
        jl_mujeres1.setModel(modelo2);
        tf_nombreP.setText("");
        tf_nacionalidad.setText("");
        tf_apellido.setText("");
        s_edad.setValue(0);
        tf_vocacion.getText();
        jd_persona.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_paisActionPerformed
        DefaultListModel modelo3 = (DefaultListModel) jl_pais.getModel();
        Pais y = new Pais(tf_nombrePa.getText(), jdc_fundacion.getDate(), tf_himno.getText(), color);
        modelo3.addElement(y);
        DefaultComboBoxModel m1 = (DefaultComboBoxModel) cb_pais.getModel();
        m1.addElement(y);
        jl_pais.setModel(modelo3);
        tf_nombrePa.setText("");
        jdc_fundacion.setDate(new Date());
        tf_himno.setText("");
        jd_pais.setVisible(false);
    }//GEN-LAST:event_jb_paisActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jd_arbol.setModal(false);
        jd_arbol.pack();
        jd_arbol.setLocationRelativeTo(this);
        jd_arbol.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        DefaultComboBoxModel mc = (DefaultComboBoxModel) cb_pais.getModel();
        DefaultComboBoxModel m = (DefaultComboBoxModel) cb_personas.getModel();
        DefaultTreeModel modeloA = (DefaultTreeModel) jt_paises.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloA.getRoot();
        DefaultMutableTreeNode raiz2 = (DefaultMutableTreeNode) raiz.getRoot();
        cb_pais.getSelectedIndex();
        String nombre = cb_pais.getSelectedItem().toString();
        String genero = ((Persona) m.getSelectedItem()).getGenero();
        DefaultMutableTreeNode h = new DefaultMutableTreeNode("Hombres");
        DefaultMutableTreeNode mu = new DefaultMutableTreeNode("Mujeres");
        int centinela = -1;
        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().equals(nombre)) {
                DefaultMutableTreeNode p = new DefaultMutableTreeNode(cb_personas.getSelectedItem());
                if (((Persona) m.getSelectedItem()).getGenero().equals("Hombre")) {
                    h.add(p);
                } else if(((Persona) m.getSelectedItem()).getGenero().equals("Mujer")) {
                    mu.add(p);
                }
                centinela = 1;
            }
        }

        if (centinela == -1) {
            DefaultMutableTreeNode n = new DefaultMutableTreeNode(nombre);
            h = new DefaultMutableTreeNode("Hombres");
            mu = new DefaultMutableTreeNode("Mujeres");
            DefaultMutableTreeNode p = new DefaultMutableTreeNode(cb_personas.getSelectedItem());
            n.add(h);
            n.add(mu);
            if (((Persona) m.getSelectedItem()).getGenero().equals("Hombre")) {
                h.add(p);
            } else if(((Persona) m.getSelectedItem()).getGenero().equals("Mujer")) {
                mu.add(p);
            }
            raiz.add(n);
        }

        jd_arbol.setVisible(false);
        modeloA.reload();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jt_paisesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_paisesMouseClicked
        if (evt.isMetaDown()) {
            int row = jt_paises.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jt_paises.setSelectionRow(row);
            Object v1
                    = jt_paises.getSelectionPath().
                            getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Persona) {
                persona_seleccionada = (Persona) nodo_seleccionado.getUserObject();
                popup1.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
            if (nodo_seleccionado.getUserObject() instanceof Pais) {
                pais_seleccionado = (Pais) nodo_seleccionado.getUserObject();
                popup2.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jt_paisesMouseClicked

    private void popup1_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup1_eliminarActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jt_paises.getModel();
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();
    }//GEN-LAST:event_popup1_eliminarActionPerformed

    private void popup2_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup2_eliminarActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jt_paises.getModel();
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();
    }//GEN-LAST:event_popup2_eliminarActionPerformed

    private void popup1_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup1_modificarActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jt_paises.getModel();
        persona_seleccionada.setNombre(JOptionPane.showInputDialog("Ingrese Nombre"));
        m.reload();

    }//GEN-LAST:event_popup1_modificarActionPerformed

    private void popup2_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup2_modificarActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jt_paises.getModel();
        pais_seleccionado.setNombre(JOptionPane.showInputDialog("Ingrese nuevo nombre del pais"));
        m.reload();
    }//GEN-LAST:event_popup2_modificarActionPerformed

    private void jt_covidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_covidMouseClicked
        if (evt.isMetaDown()) {
            int row = jt_covid.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jt_covid.setSelectionRow(row);
            Object v2 = jt_covid.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v2;
            if (nodo_seleccionado.getUserObject() instanceof Persona) {
                persona_seleccionada = (Persona) nodo_seleccionado.getUserObject();
                popup3.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
            if (nodo_seleccionado.getUserObject() instanceof Pais) {
                pais_seleccionado = (Pais) nodo_seleccionado.getUserObject();
                popup4.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jt_covidMouseClicked

    private void popup3_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup3_modificarActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jt_covid.getModel();
        pais_seleccionado.setNombre(JOptionPane.showInputDialog("Ingrese nuevo nombre del pais"));
        m.reload();
    }//GEN-LAST:event_popup3_modificarActionPerformed

    private void popup3_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup3_eliminarActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jt_covid.getModel();
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();
    }//GEN-LAST:event_popup3_eliminarActionPerformed

    private void popup4_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup4_modificarActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jt_covid.getModel();
        pais_seleccionado.setNombre(JOptionPane.showInputDialog("Ingrese nuevo nombre de la persona"));
        m.reload();
    }//GEN-LAST:event_popup4_modificarActionPerformed

    private void popup4_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popup4_eliminarActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) jt_covid.getModel();
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();
    }//GEN-LAST:event_popup4_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_covid;
    private javax.swing.ButtonGroup bg_genero;
    private javax.swing.ButtonGroup bg_titulo;
    private javax.swing.JComboBox<String> cb_pais;
    private javax.swing.JComboBox<String> cb_personas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JButton jb_agregarP;
    private javax.swing.JButton jb_agregarPa;
    private javax.swing.JButton jb_colorb;
    private javax.swing.JButton jb_pais;
    private javax.swing.JDialog jd_arbol;
    private javax.swing.JDialog jd_pais;
    private javax.swing.JDialog jd_persona;
    private com.toedter.calendar.JDateChooser jdc_fundacion;
    private javax.swing.JList<String> jl_hombres1;
    private javax.swing.JList<String> jl_mujeres1;
    private javax.swing.JList<String> jl_pais;
    private javax.swing.JTree jt_covid;
    private javax.swing.JTree jt_paises;
    private javax.swing.JPopupMenu popup1;
    private javax.swing.JMenuItem popup1_agregar;
    private javax.swing.JMenuItem popup1_eliminar;
    private javax.swing.JMenuItem popup1_modificar;
    private javax.swing.JPopupMenu popup2;
    private javax.swing.JMenuItem popup2_agregar;
    private javax.swing.JMenuItem popup2_eliminar;
    private javax.swing.JMenuItem popup2_modificar;
    private javax.swing.JPopupMenu popup3;
    private javax.swing.JMenuItem popup3_agregar;
    private javax.swing.JMenuItem popup3_eliminar;
    private javax.swing.JMenuItem popup3_modificar;
    private javax.swing.JPopupMenu popup4;
    private javax.swing.JMenuItem popup4_agregar;
    private javax.swing.JMenuItem popup4_eliminar;
    private javax.swing.JMenuItem popup4_modificar;
    private javax.swing.JRadioButton rb_f;
    private javax.swing.JRadioButton rb_m;
    private javax.swing.JRadioButton rb_nega;
    private javax.swing.JRadioButton rb_noviembre;
    private javax.swing.JRadioButton rb_pos;
    private javax.swing.JRadioButton rb_simon;
    private javax.swing.JSpinner s_edad;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JTextField tf_himno;
    private javax.swing.JTextField tf_nacionalidad;
    private javax.swing.JTextField tf_nombreP;
    private javax.swing.JTextField tf_nombrePa;
    private javax.swing.JTextField tf_vocacion;
    // End of variables declaration//GEN-END:variables
    Color color;
    DefaultMutableTreeNode nodo_seleccionado;
    Persona persona_seleccionada;
    Pais pais_seleccionado;
}
